name: Python Tests

on:
  pull_request:
    branches:
      - develop   # O la rama donde estés haciendo los PRs (por ejemplo, 'develop' si usas esa)
  push:
    branches:
      - main   # Si deseas que los tests también se ejecuten en cada push a la rama principal

jobs:
  test:
    runs-on: windows-latest  # Puedes cambiar esto si prefieres un sistema diferente (por ejemplo, 'windows-latest')

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2  # Descarga el código del repositorio en el runner

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.2'  # Asegúrate de usar la versión de Python que estés usando localmente

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instalar las dependencias de tu proyecto

    - name: Install pylint
      run: pip install pylint  # Instalar pylint

    - name: Run pylint
      run: pylint **/*.py  # Analiza todos los archivos .py en el proyecto, incluidos subdirectorios

    - name: Install black
      run: pip install black

    - name: Format code with black
      run: black .  # Ejecuta black en todos los archivos Python en el proyecto

    - name: Install coverage
      run: pip install coverage  # Instalar coverage

    - name: Run tests with coverage
      run: |
        coverage run -m pytest  # Ejecuta los tests con coverage
        coverage report  # Muestra el reporte de cobertura en la salida
        coverage html  # (Opcional) Genera un reporte en HTML, puedes eliminar este paso si no lo necesitas

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Ejecuta los tests con pytest
