name: Python Tests

on:
  pull_request:
    branches:
      - develop  
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest  # Usa Linux para mejor compatibilidad y velocidad

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install black
      run: pip install black  # Instala black antes de usarlo

    - name: Check code formatting with black
      run: black --check .

    - name: Format code with black
      run: black .

    - name: Run tests with coverage
      run: |
        coverage run -m pytest  
        coverage report --fail-under=100  # Bloquea si la cobertura es menor al 100%
        coverage xml  

    - name: Upload coverage report
      uses: actions/upload-pages-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
