name: Python Tests

on:
  pull_request:
    branches:
      - develop   # O la rama donde estés haciendo los PRs
  push:
    branches:
      - main   # Si deseas que los tests se ejecuten en cada push a la rama principal

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install black
      run: pip install black

    - name: Format code with black
      run: black .

    - name: Install coverage
      run: pip install coverage

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage html
        coverage xml

    - name: List generated files
      run: dir  # Esto mostrará los archivos del directorio actual en Windows

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./coverage.xml
