name: Python Tests

on:
  pull_request:
    branches:
      - develop  
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest  # Usa Linux para mejor compatibilidad y velocidad

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install black
      run: pip install black
  
    - name: Format code with black
      run: black .