name: Python Tests

on:
  pull_request:
    branches:
      - develop  
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest  # Usa Linux para mejor compatibilidad y velocidad

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install black
      run: pip install black
  
    - name: Format code with black
      run: black .
  
    - name: Run tests with coverage
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)  # Asegurar que el código es importable
        coverage run -m pytest -v --disable-warnings || echo "Tests failed!"
        coverage report --fail-under=100 || echo "Coverage below 100%"
        coverage xml || echo "Failed to generate coverage.xml"


    - name: Prepare coverage report directory
      run: |
        mkdir coverage-report   # Crea el directorio para el reporte
        mv coverage.xml coverage-report/  # Mueve el archivo XML al directorio

    - name: List files in workspace (debugging)
      run: ls -R

    - name: Upload coverage report
      uses: actions/upload-pages-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
